# Generated by Django 5.0.7 on 2024-07-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='توضیح')),
            ],
            options={
                'verbose_name': 'توضیح',
                'verbose_name_plural': 'توضیحات',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='جنس رویه')),
                ('slug', models.CharField(db_index=True, default='', max_length=25, unique=True, verbose_name='اسلاگ در url')),
            ],
            options={
                'verbose_name': 'جنس رویه',
                'verbose_name_plural': 'جنس های رویه',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.IntegerField(blank=True, null=True, verbose_name='اندازه')),
            ],
            options={
                'verbose_name': 'اندازه',
                'verbose_name_plural': 'اندازه ها',
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('brand', models.CharField(max_length=30, verbose_name='برند')),
                ('property', models.CharField(max_length=30, verbose_name='ویژگی')),
                ('color', models.CharField(max_length=30, verbose_name='رنگ')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('photo', models.ImageField(upload_to='files/shoes', verbose_name='عکس')),
                ('gender', models.CharField(max_length=10, verbose_name='جنسیت')),
                ('slug', models.CharField(db_index=True, default='', max_length=50, verbose_name='اسلاگ در url')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.discription', verbose_name='توضیح')),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.kind', verbose_name='جنس رویه')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.size', verbose_name='اندازه')),
            ],
            options={
                'verbose_name': 'کفش',
                'verbose_name_plural': 'کفش ها',
            },
        ),
    ]
