# Generated by Django 5.0.7 on 2024-07-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_color_alter_shoe_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='color',
        ),
        migrations.AddField(
            model_name='shoe',
            name='color',
            field=models.ManyToManyField(to='shoes.color', verbose_name='رنگ'),
        ),
    ]
