# Generated by Django 5.0.7 on 2024-07-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_remove_shoe_color_shoe_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='size',
        ),
        migrations.AddField(
            model_name='shoe',
            name='size',
            field=models.ManyToManyField(to='shoes.size', verbose_name='اندازه'),
        ),
    ]
