# Generated by Django 5.0.2 on 2024-07-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_remove_shoe_size_shoe_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='slug',
        ),
    ]
