# Generated by Django 5.0.7 on 2024-07-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_remove_color_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ImageField(upload_to='files/shoes', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس ها',
            },
        ),
        migrations.AddField(
            model_name='shoe',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoe',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='photo',
        ),
        migrations.AddField(
            model_name='shoe',
            name='photo',
            field=models.ManyToManyField(to='shoes.photo', verbose_name='عکس'),
        ),
    ]
