# Generated by Django 5.0.7 on 2024-07-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_photo_shoe_is_sale_shoe_sale_price_remove_shoe_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='shoe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='files/shose', verbose_name='عکس'),
        ),
    ]
