# Generated by Django 5.0.7 on 2024-07-22 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_shoecolorinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeColorSizeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.color')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoe')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.size')),
            ],
            options={
                'verbose_name': 'موجودی کفش بر اساس رنگ و سایز',
                'verbose_name_plural': 'موجودی کفش ها بر اساس رنگ و سایز',
                'unique_together': {('shoe', 'color', 'size')},
            },
        ),
        migrations.DeleteModel(
            name='ShoeColorInventory',
        ),
    ]
