# Generated by Django 5.0.7 on 2024-07-22 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0011_shoecolorinventory_shoesizeinventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoesizeinventory',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.size'),
        ),
    ]
