# Generated by Django 5.0.7 on 2024-08-01 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0013_category_shoe_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش ها'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='shoe',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.category', verbose_name='دسته بندی'),
        ),
    ]
