# Generated by Django 5.0.7 on 2024-08-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0015_remove_shoe_quantity_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد خرید'},
        ),
    ]
