# Generated by Django 5.0.7 on 2024-08-04 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0016_alter_cart_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='photo',
        ),
        migrations.CreateModel(
            name='ShoeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='files/shoes')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shoes.shoe')),
            ],
        ),
    ]
