# Generated by Django 5.0.7 on 2024-08-04 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0017_remove_shoe_photo_shoeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='files/shose', verbose_name='عکس منتخب'),
        ),
        migrations.AlterField(
            model_name='shoeimage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='files/shoes', verbose_name='دیگر عکس ها'),
        ),
        migrations.AlterField(
            model_name='shoeimage',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shoes.shoe', verbose_name='عکس کفش'),
        ),
    ]
