# Generated by Django 5.0.7 on 2024-08-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0018_shoe_photo_alter_shoeimage_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoeimage',
            old_name='photo',
            new_name='image',
        ),
    ]
