# Generated by Django 5.0.7 on 2024-08-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0019_rename_photo_shoeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='files/shoes', verbose_name='عکس منتخب'),
        ),
    ]
